/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Achievement = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'images' : IDL.Opt(IDL.Vec(ExternalBlob)),
});
export const LockerBill = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'date' : IDL.Text,
  'author' : IDL.Principal,
  'image' : ExternalBlob,
  'comments' : IDL.Text,
  'amount' : IDL.Text,
});
export const LockerDocument = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'file' : ExternalBlob,
  'tags' : IDL.Text,
  'description' : IDL.Text,
  'dateUploaded' : IDL.Text,
  'author' : IDL.Principal,
});
export const DriveLink = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'dateAdded' : IDL.Text,
});
export const EquipmentItem = IDL.Record({
  'id' : IDL.Text,
  'purchaseDate' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'addedBy' : IDL.Principal,
  'quantity' : IDL.Text,
  'image' : ExternalBlob,
  'comments' : IDL.Text,
  'unitPrice' : IDL.Text,
});
export const Event = IDL.Record({
  'title' : IDL.Text,
  'date' : IDL.Text,
  'description' : IDL.Text,
  'location' : IDL.Opt(IDL.Text),
  'images' : IDL.Opt(IDL.Vec(ExternalBlob)),
});
export const Person = IDL.Record({
  'id' : IDL.Principal,
  'contactInfo' : IDL.Text,
  'name' : IDL.Text,
  'roleDescription' : IDL.Text,
  'image' : ExternalBlob,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'joinDate' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAchievement' : IDL.Func([Achievement], [], []),
  'addBill' : IDL.Func([LockerBill], [IDL.Bool], []),
  'addDocument' : IDL.Func([LockerDocument], [IDL.Bool], []),
  'addDriveLink' : IDL.Func([DriveLink], [IDL.Bool], []),
  'addEquipment' : IDL.Func([EquipmentItem], [IDL.Bool], []),
  'addEvent' : IDL.Func([Event], [], []),
  'addPerson' : IDL.Func([Person], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteBill' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteDriveLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'deleteEquipment' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
  'getAllBills' : IDL.Func([], [IDL.Vec(LockerBill)], ['query']),
  'getAllDocuments' : IDL.Func([], [IDL.Vec(LockerDocument)], ['query']),
  'getAllDriveLinks' : IDL.Func([], [IDL.Vec(DriveLink)], ['query']),
  'getAllEquipment' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removeEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'removePerson' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateAchievement' : IDL.Func([IDL.Text, Achievement], [IDL.Bool], []),
  'updateEvent' : IDL.Func([IDL.Text, Event], [IDL.Bool], []),
  'updatePerson' : IDL.Func([IDL.Principal, Person], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Achievement = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'images' : IDL.Opt(IDL.Vec(ExternalBlob)),
  });
  const LockerBill = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'date' : IDL.Text,
    'author' : IDL.Principal,
    'image' : ExternalBlob,
    'comments' : IDL.Text,
    'amount' : IDL.Text,
  });
  const LockerDocument = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'file' : ExternalBlob,
    'tags' : IDL.Text,
    'description' : IDL.Text,
    'dateUploaded' : IDL.Text,
    'author' : IDL.Principal,
  });
  const DriveLink = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'dateAdded' : IDL.Text,
  });
  const EquipmentItem = IDL.Record({
    'id' : IDL.Text,
    'purchaseDate' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'addedBy' : IDL.Principal,
    'quantity' : IDL.Text,
    'image' : ExternalBlob,
    'comments' : IDL.Text,
    'unitPrice' : IDL.Text,
  });
  const Event = IDL.Record({
    'title' : IDL.Text,
    'date' : IDL.Text,
    'description' : IDL.Text,
    'location' : IDL.Opt(IDL.Text),
    'images' : IDL.Opt(IDL.Vec(ExternalBlob)),
  });
  const Person = IDL.Record({
    'id' : IDL.Principal,
    'contactInfo' : IDL.Text,
    'name' : IDL.Text,
    'roleDescription' : IDL.Text,
    'image' : ExternalBlob,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'joinDate' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAchievement' : IDL.Func([Achievement], [], []),
    'addBill' : IDL.Func([LockerBill], [IDL.Bool], []),
    'addDocument' : IDL.Func([LockerDocument], [IDL.Bool], []),
    'addDriveLink' : IDL.Func([DriveLink], [IDL.Bool], []),
    'addEquipment' : IDL.Func([EquipmentItem], [IDL.Bool], []),
    'addEvent' : IDL.Func([Event], [], []),
    'addPerson' : IDL.Func([Person], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteBill' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDocument' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteDriveLink' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'deleteEquipment' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAllAchievements' : IDL.Func([], [IDL.Vec(Achievement)], ['query']),
    'getAllBills' : IDL.Func([], [IDL.Vec(LockerBill)], ['query']),
    'getAllDocuments' : IDL.Func([], [IDL.Vec(LockerDocument)], ['query']),
    'getAllDriveLinks' : IDL.Func([], [IDL.Vec(DriveLink)], ['query']),
    'getAllEquipment' : IDL.Func([], [IDL.Vec(EquipmentItem)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllPeople' : IDL.Func([], [IDL.Vec(Person)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeAchievement' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removeEvent' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'removePerson' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateAchievement' : IDL.Func([IDL.Text, Achievement], [IDL.Bool], []),
    'updateEvent' : IDL.Func([IDL.Text, Event], [IDL.Bool], []),
    'updatePerson' : IDL.Func([IDL.Principal, Person], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };