/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LockerDocument {
    id: string;
    title: string;
    file: ExternalBlob;
    tags: string;
    description: string;
    dateUploaded: string;
    author: Principal;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Event {
    title: string;
    date: string;
    description: string;
    location?: string;
    images?: Array<ExternalBlob>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface DriveLink {
    id: string;
    url: string;
    title: string;
    description: string;
    author: Principal;
    dateAdded: string;
}
export interface FeedbackEntry {
    id: bigint;
    submitter: Principal;
    message: string;
    timestamp: bigint;
    category: string;
}
export interface Achievement {
    title: string;
    date: string;
    description: string;
    images?: Array<ExternalBlob>;
}
export interface EquipmentItem {
    id: string;
    purchaseDate: string;
    name: string;
    description: string;
    addedBy: Principal;
    quantity: string;
    image: ExternalBlob;
    comments: string;
    unitPrice: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export interface LockerAccessRequest {
    status: RequestStatus;
    requester: Principal;
    decisionTimestamp?: bigint;
    name: string;
    requestTimestamp: bigint;
}
export interface LockerBill {
    id: string;
    title: string;
    date: string;
    author: Principal;
    image: ExternalBlob;
    comments: string;
    amount: string;
}
export interface Person {
    id: Principal;
    contactInfo: string;
    name: string;
    roleDescription: string;
    image: ExternalBlob;
}
export interface UserProfile {
    joinDate: string;
    name: string;
    email?: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum RequestStatus {
    pending = "pending",
    denied = "denied",
    approved = "approved"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAchievement(achievement: Achievement): Promise<void>;
    addBill(bill: LockerBill): Promise<boolean>;
    addDocument(doc: LockerDocument): Promise<boolean>;
    addDriveLink(link: DriveLink): Promise<boolean>;
    addEquipment(equipmentItem: EquipmentItem): Promise<boolean>;
    addEvent(event: Event): Promise<void>;
    addPerson(person: Person): Promise<void>;
    approveLockerAccessRequest(requester: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteBill(id: string): Promise<boolean>;
    deleteDocument(id: string): Promise<boolean>;
    deleteDriveLink(id: string): Promise<boolean>;
    deleteEquipment(id: string): Promise<boolean>;
    denyLockerAccessRequest(requester: Principal): Promise<void>;
    getAllAchievements(): Promise<Array<Achievement>>;
    getAllBills(): Promise<Array<LockerBill>>;
    getAllDocuments(): Promise<Array<LockerDocument>>;
    getAllDriveLinks(): Promise<Array<DriveLink>>;
    getAllEquipment(): Promise<Array<EquipmentItem>>;
    getAllEvents(): Promise<Array<Event>>;
    getAllFeedback(): Promise<Array<FeedbackEntry>>;
    getAllPeople(): Promise<Array<Person>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLockerAccessRequests(): Promise<Array<LockerAccessRequest>>;
    getMyLockerAccessStatus(): Promise<RequestStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    isLockerAccessGrantedQuery(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    removeAchievement(title: string): Promise<boolean>;
    removeEvent(title: string): Promise<boolean>;
    removePerson(principal: Principal): Promise<boolean>;
    requestApproval(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    submitFeedback(category: string, message: string): Promise<void>;
    submitLockerAccessRequest(name: string): Promise<void>;
    updateAchievement(title: string, updatedAchievement: Achievement): Promise<boolean>;
    updateEvent(title: string, updatedEvent: Event): Promise<boolean>;
    updatePerson(principal: Principal, updatedPerson: Person): Promise<boolean>;
}
import type { Achievement as _Achievement, ApprovalStatus as _ApprovalStatus, EquipmentItem as _EquipmentItem, Event as _Event, ExternalBlob as _ExternalBlob, LockerAccessRequest as _LockerAccessRequest, LockerBill as _LockerBill, LockerDocument as _LockerDocument, Person as _Person, RequestStatus as _RequestStatus, UserApprovalInfo as _UserApprovalInfo, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAchievement(arg0: Achievement): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAchievement(await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addBill(arg0: LockerBill): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addBill(await to_candid_LockerBill_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addBill(await to_candid_LockerBill_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDocument(arg0: LockerDocument): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addDocument(await to_candid_LockerDocument_n14(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDocument(await to_candid_LockerDocument_n14(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addDriveLink(arg0: DriveLink): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addDriveLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addDriveLink(arg0);
            return result;
        }
    }
    async addEquipment(arg0: EquipmentItem): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.addEquipment(await to_candid_EquipmentItem_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEquipment(await to_candid_EquipmentItem_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addEvent(arg0: Event): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEvent(await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEvent(await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addPerson(arg0: Person): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addPerson(await to_candid_Person_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPerson(await to_candid_Person_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async approveLockerAccessRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveLockerAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveLockerAccessRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteBill(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBill(arg0);
            return result;
        }
    }
    async deleteDocument(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDocument(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDocument(arg0);
            return result;
        }
    }
    async deleteDriveLink(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteDriveLink(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteDriveLink(arg0);
            return result;
        }
    }
    async deleteEquipment(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEquipment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEquipment(arg0);
            return result;
        }
    }
    async denyLockerAccessRequest(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.denyLockerAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.denyLockerAccessRequest(arg0);
            return result;
        }
    }
    async getAllAchievements(): Promise<Array<Achievement>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAchievements();
                return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAchievements();
            return from_candid_vec_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllBills(): Promise<Array<LockerBill>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBills();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBills();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDocuments(): Promise<Array<LockerDocument>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDocuments();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDocuments();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDriveLinks(): Promise<Array<DriveLink>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDriveLinks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDriveLinks();
            return result;
        }
    }
    async getAllEquipment(): Promise<Array<EquipmentItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipment();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipment();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllEvents(): Promise<Array<Event>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEvents();
                return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEvents();
            return from_candid_vec_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllFeedback(): Promise<Array<FeedbackEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFeedback();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFeedback();
            return result;
        }
    }
    async getAllPeople(): Promise<Array<Person>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPeople();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPeople();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLockerAccessRequests(): Promise<Array<LockerAccessRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLockerAccessRequests();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLockerAccessRequests();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyLockerAccessStatus(): Promise<RequestStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyLockerAccessStatus();
                return from_candid_RequestStatus_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyLockerAccessStatus();
            return from_candid_RequestStatus_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async isLockerAccessGrantedQuery(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isLockerAccessGrantedQuery();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isLockerAccessGrantedQuery();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeAchievement(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAchievement(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAchievement(arg0);
            return result;
        }
    }
    async removeEvent(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeEvent(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeEvent(arg0);
            return result;
        }
    }
    async removePerson(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removePerson(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePerson(arg0);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n62(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n64(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async submitFeedback(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFeedback(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFeedback(arg0, arg1);
            return result;
        }
    }
    async submitLockerAccessRequest(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitLockerAccessRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitLockerAccessRequest(arg0);
            return result;
        }
    }
    async updateAchievement(arg0: string, arg1: Achievement): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAchievement(arg0, await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAchievement(arg0, await to_candid_Achievement_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateEvent(arg0: string, arg1: Event): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEvent(arg0, await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEvent(arg0, await to_candid_Event_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePerson(arg0: Principal, arg1: Person): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePerson(arg0, await to_candid_Person_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePerson(arg0, await to_candid_Person_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_Achievement_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Achievement): Promise<Achievement> {
    return await from_candid_record_n26(_uploadFile, _downloadFile, value);
}
function from_candid_ApprovalStatus_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
async function from_candid_EquipmentItem_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentItem): Promise<EquipmentItem> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
async function from_candid_Event_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Event): Promise<Event> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_LockerAccessRequest_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LockerAccessRequest): LockerAccessRequest {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function from_candid_LockerBill_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LockerBill): Promise<LockerBill> {
    return await from_candid_record_n32(_uploadFile, _downloadFile, value);
}
async function from_candid_LockerDocument_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LockerDocument): Promise<LockerDocument> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_Person_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Person): Promise<Person> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
function from_candid_RequestStatus_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RequestStatus): RequestStatus {
    return from_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n48(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_ExternalBlob>]): Promise<Array<ExternalBlob> | null> {
    return value.length === 0 ? null : await from_candid_vec_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n47(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    images: [] | [Array<_ExternalBlob>];
}): Promise<{
    title: string;
    date: string;
    description: string;
    images?: Array<ExternalBlob>;
}> {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        images: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.images))
    };
}
async function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    date: string;
    author: Principal;
    image: _ExternalBlob;
    comments: string;
    amount: string;
}): Promise<{
    id: string;
    title: string;
    date: string;
    author: Principal;
    image: ExternalBlob;
    comments: string;
    amount: string;
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        author: value.author,
        image: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.image),
        comments: value.comments,
        amount: value.amount
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: _ExternalBlob;
    tags: string;
    description: string;
    dateUploaded: string;
    author: Principal;
}): Promise<{
    id: string;
    title: string;
    file: ExternalBlob;
    tags: string;
    description: string;
    dateUploaded: string;
    author: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.file),
        tags: value.tags,
        description: value.description,
        dateUploaded: value.dateUploaded,
        author: value.author
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    purchaseDate: string;
    name: string;
    description: string;
    addedBy: Principal;
    quantity: string;
    image: _ExternalBlob;
    comments: string;
    unitPrice: string;
}): Promise<{
    id: string;
    purchaseDate: string;
    name: string;
    description: string;
    addedBy: Principal;
    quantity: string;
    image: ExternalBlob;
    comments: string;
    unitPrice: string;
}> {
    return {
        id: value.id,
        purchaseDate: value.purchaseDate,
        name: value.name,
        description: value.description,
        addedBy: value.addedBy,
        quantity: value.quantity,
        image: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.image),
        comments: value.comments,
        unitPrice: value.unitPrice
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    location: [] | [string];
    images: [] | [Array<_ExternalBlob>];
}): Promise<{
    title: string;
    date: string;
    description: string;
    location?: string;
    images?: Array<ExternalBlob>;
}> {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        location: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.location)),
        images: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.images))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo: string;
    name: string;
    roleDescription: string;
    image: _ExternalBlob;
}): Promise<{
    id: Principal;
    contactInfo: string;
    name: string;
    roleDescription: string;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        roleDescription: value.roleDescription,
        image: await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value.image)
    };
}
function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    joinDate: string;
    name: string;
    email: [] | [string];
}): {
    joinDate: string;
    name: string;
    email?: string;
} {
    return {
        joinDate: value.joinDate,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n42(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _RequestStatus;
    requester: Principal;
    decisionTimestamp: [] | [bigint];
    name: string;
    requestTimestamp: bigint;
}): {
    status: RequestStatus;
    requester: Principal;
    decisionTimestamp?: bigint;
    name: string;
    requestTimestamp: bigint;
} {
    return {
        status: from_candid_RequestStatus_n54(_uploadFile, _downloadFile, value.status),
        requester: value.requester,
        decisionTimestamp: record_opt_to_undefined(from_candid_opt_n56(_uploadFile, _downloadFile, value.decisionTimestamp)),
        name: value.name,
        requestTimestamp: value.requestTimestamp
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n60(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    denied: null;
} | {
    approved: null;
}): RequestStatus {
    return "pending" in value ? RequestStatus.pending : "denied" in value ? RequestStatus.denied : "approved" in value ? RequestStatus.approved : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
async function from_candid_vec_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Achievement>): Promise<Array<Achievement>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Achievement_n25(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LockerBill>): Promise<Array<LockerBill>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LockerBill_n31(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LockerDocument>): Promise<Array<LockerDocument>> {
    return await Promise.all(value.map(async (x)=>await from_candid_LockerDocument_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EquipmentItem>): Promise<Array<EquipmentItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EquipmentItem_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Event>): Promise<Array<Event>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Event_n40(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Person>): Promise<Array<Person>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Person_n44(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LockerAccessRequest>): Array<LockerAccessRequest> {
    return value.map((x)=>from_candid_LockerAccessRequest_n52(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n58(_uploadFile, _downloadFile, x));
}
async function to_candid_Achievement_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Achievement): Promise<_Achievement> {
    return await to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_ApprovalStatus_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_EquipmentItem_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentItem): Promise<_EquipmentItem> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_Event_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Event): Promise<_Event> {
    return await to_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_LockerBill_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LockerBill): Promise<_LockerBill> {
    return await to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_LockerDocument_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LockerDocument): Promise<_LockerDocument> {
    return await to_candid_record_n15(_uploadFile, _downloadFile, value);
}
async function to_candid_Person_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Person): Promise<_Person> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n63(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    date: string;
    author: Principal;
    image: ExternalBlob;
    comments: string;
    amount: string;
}): Promise<{
    id: string;
    title: string;
    date: string;
    author: Principal;
    image: _ExternalBlob;
    comments: string;
    amount: string;
}> {
    return {
        id: value.id,
        title: value.title,
        date: value.date,
        author: value.author,
        image: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image),
        comments: value.comments,
        amount: value.amount
    };
}
async function to_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    file: ExternalBlob;
    tags: string;
    description: string;
    dateUploaded: string;
    author: Principal;
}): Promise<{
    id: string;
    title: string;
    file: _ExternalBlob;
    tags: string;
    description: string;
    dateUploaded: string;
    author: Principal;
}> {
    return {
        id: value.id,
        title: value.title,
        file: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.file),
        tags: value.tags,
        description: value.description,
        dateUploaded: value.dateUploaded,
        author: value.author
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    purchaseDate: string;
    name: string;
    description: string;
    addedBy: Principal;
    quantity: string;
    image: ExternalBlob;
    comments: string;
    unitPrice: string;
}): Promise<{
    id: string;
    purchaseDate: string;
    name: string;
    description: string;
    addedBy: Principal;
    quantity: string;
    image: _ExternalBlob;
    comments: string;
    unitPrice: string;
}> {
    return {
        id: value.id,
        purchaseDate: value.purchaseDate,
        name: value.name,
        description: value.description,
        addedBy: value.addedBy,
        quantity: value.quantity,
        image: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image),
        comments: value.comments,
        unitPrice: value.unitPrice
    };
}
async function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    location?: string;
    images?: Array<ExternalBlob>;
}): Promise<{
    title: string;
    date: string;
    description: string;
    location: [] | [string];
    images: [] | [Array<_ExternalBlob>];
}> {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        location: value.location ? candid_some(value.location) : candid_none(),
        images: value.images ? candid_some(await to_candid_vec_n10(_uploadFile, _downloadFile, value.images)) : candid_none()
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo: string;
    name: string;
    roleDescription: string;
    image: ExternalBlob;
}): Promise<{
    id: Principal;
    contactInfo: string;
    name: string;
    roleDescription: string;
    image: _ExternalBlob;
}> {
    return {
        id: value.id,
        contactInfo: value.contactInfo,
        name: value.name,
        roleDescription: value.roleDescription,
        image: await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    joinDate: string;
    name: string;
    email?: string;
}): {
    joinDate: string;
    name: string;
    email: [] | [string];
} {
    return {
        joinDate: value.joinDate,
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
async function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    date: string;
    description: string;
    images?: Array<ExternalBlob>;
}): Promise<{
    title: string;
    date: string;
    description: string;
    images: [] | [Array<_ExternalBlob>];
}> {
    return {
        title: value.title,
        date: value.date,
        description: value.description,
        images: value.images ? candid_some(await to_candid_vec_n10(_uploadFile, _downloadFile, value.images)) : candid_none()
    };
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
async function to_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n11(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
