/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Achievement {
  'title' : string,
  'date' : string,
  'description' : string,
  'images' : [] | [Array<ExternalBlob>],
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface DriveLink {
  'id' : string,
  'url' : string,
  'title' : string,
  'description' : string,
  'author' : Principal,
  'dateAdded' : string,
}
export interface EquipmentItem {
  'id' : string,
  'purchaseDate' : string,
  'name' : string,
  'description' : string,
  'addedBy' : Principal,
  'quantity' : string,
  'image' : ExternalBlob,
  'comments' : string,
  'unitPrice' : string,
}
export interface Event {
  'title' : string,
  'date' : string,
  'description' : string,
  'location' : [] | [string],
  'images' : [] | [Array<ExternalBlob>],
}
export type ExternalBlob = Uint8Array;
export interface FeedbackEntry {
  'id' : bigint,
  'submitter' : Principal,
  'message' : string,
  'timestamp' : bigint,
  'category' : string,
}
export interface LockerAccessRequest {
  'status' : RequestStatus,
  'requester' : Principal,
  'decisionTimestamp' : [] | [bigint],
  'name' : string,
  'requestTimestamp' : bigint,
}
export interface LockerBill {
  'id' : string,
  'title' : string,
  'date' : string,
  'author' : Principal,
  'image' : ExternalBlob,
  'comments' : string,
  'amount' : string,
}
export interface LockerDocument {
  'id' : string,
  'title' : string,
  'file' : ExternalBlob,
  'tags' : string,
  'description' : string,
  'dateUploaded' : string,
  'author' : Principal,
}
export interface Person {
  'id' : Principal,
  'contactInfo' : string,
  'name' : string,
  'roleDescription' : string,
  'image' : ExternalBlob,
}
export type RequestStatus = { 'pending' : null } |
  { 'denied' : null } |
  { 'approved' : null };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'joinDate' : string,
  'name' : string,
  'email' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAchievement' : ActorMethod<[Achievement], undefined>,
  'addBill' : ActorMethod<[LockerBill], boolean>,
  'addDocument' : ActorMethod<[LockerDocument], boolean>,
  'addDriveLink' : ActorMethod<[DriveLink], boolean>,
  'addEquipment' : ActorMethod<[EquipmentItem], boolean>,
  'addEvent' : ActorMethod<[Event], undefined>,
  'addPerson' : ActorMethod<[Person], undefined>,
  'approveLockerAccessRequest' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteBill' : ActorMethod<[string], boolean>,
  'deleteDocument' : ActorMethod<[string], boolean>,
  'deleteDriveLink' : ActorMethod<[string], boolean>,
  'deleteEquipment' : ActorMethod<[string], boolean>,
  'denyLockerAccessRequest' : ActorMethod<[Principal], undefined>,
  'getAllAchievements' : ActorMethod<[], Array<Achievement>>,
  'getAllBills' : ActorMethod<[], Array<LockerBill>>,
  'getAllDocuments' : ActorMethod<[], Array<LockerDocument>>,
  'getAllDriveLinks' : ActorMethod<[], Array<DriveLink>>,
  'getAllEquipment' : ActorMethod<[], Array<EquipmentItem>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllFeedback' : ActorMethod<[], Array<FeedbackEntry>>,
  'getAllPeople' : ActorMethod<[], Array<Person>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLockerAccessRequests' : ActorMethod<[], Array<LockerAccessRequest>>,
  'getMyLockerAccessStatus' : ActorMethod<[], RequestStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isLockerAccessGrantedQuery' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'removeAchievement' : ActorMethod<[string], boolean>,
  'removeEvent' : ActorMethod<[string], boolean>,
  'removePerson' : ActorMethod<[Principal], boolean>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'submitFeedback' : ActorMethod<[string, string], undefined>,
  'submitLockerAccessRequest' : ActorMethod<[string], undefined>,
  'updateAchievement' : ActorMethod<[string, Achievement], boolean>,
  'updateEvent' : ActorMethod<[string, Event], boolean>,
  'updatePerson' : ActorMethod<[Principal, Person], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];